services:
  assisted-rag:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - assisted-rag:latest
    image: assisted-rag:latest
    command: runserver
    volumes:
      - /root/.ipython/profile_default/history
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  assisted-rag-prod:
    extends: assisted-rag
    ports:
      - "9009:8000"

  assisted-rag-dev:
    extends: assisted-rag
    profiles:
      - dev
    command: bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "9011:8000"

  assisted-rag-ipython:
    extends: assisted-rag
    profiles:
      - ipython
    command: ipython
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "9012:8000"

  neo4j:
    image: neo4j:2025.01.0-bullseye
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
        - /.data/neo4j/logs:/logs
        - /.data/neo4j/config:/config
        - /.data/neo4j/data:/data
        - /.data/neo4j/plugins:/plugins
    environment:
      # - NEO4J_AUTH=neo4j/blahblah  # Just for testing
      - NEO4J_AUTH=none
    restart: always

